### ISSUE TITLE
TypeError:can't convert np.ndarray of type numpy.bool_

### ISSUE THREAD

**Issue by menggehe** [graykode/xlnet-Pytorch#6]
Traceback (most recent call last):
  File "main.py", line 89, in <module>
    num_predict=args.num_predict)
  File "/home/hemengge/xlnet-pytorch/data_utils.py", line 335, in make_permute
    is_masked = torch.Tensor(feature.pop("is_masked"))

TypeError: can't convert np.ndarray of type numpy.bool_. The only supported types are: double, float, float16, int64, int32, and uint8

**Comment by LorraineLo4** [comment]
Having the same issue.

**Comment by xingchensong** [comment]
`is_masked = torch.ByteTensor(feature.pop("is_masked").copy().astype(np.uint8))` @menggehe
